services:
  app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - mynetwork

networks:
  mynetwork:
